#!/bin/bash

script_location="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fileConfigLocation="$script_location/fpark.service"

sudo cp $fileConfigLocation /etc/systemd/system/fpark.service
exec_fpark=$(which fpark)
escaped="${exec_fpark//\//\\/}"
sudo sed -i -e "s/@exec/${escaped}/g" /etc/systemd/system/fpark.service

sudo adduser fpark --no-create-home --disabled-password --system --group
mkdir /var/www/fpark
sudo cp "$script_location/../src/config.json" /var/www/fpark/fpark.config.json
sudo chown -R fpark:fpark /var/www/fpark

sudo systemctl daemon-reload
sudo systemctl enable fpark
sudo systemctl start fpark
